Hands-on Lab: Interactive Visual Analytics with Folium

Estimated time needed: 40 minutes

The launch success rate may depend on many factors such as payload mass, orbit type, and so on. It may also depend on the location and proximities of a launch site, i.e., the initial position of rocket trajectories. Finding an optimal location for building a launch site certainly involves many factors and hopefully we could discover some of the factors by analyzing the existing launch site locations.

In the previous exploratory data analysis labs, you have visualized the SpaceX launch dataset using matplotlib and seaborn and discovered some preliminary correlations between the launch site and success rates. In this lab, you will be performing more interactive visual analytics using Folium.

Objectives

This lab contains the following tasks:

TASK 1: Mark all launch sites on a map

TASK 2: Mark the success/failed launches for each site on the map

TASK 3: Calculate the distances between a launch site to its proximities

After completed the above tasks, you should be able to find some geographical patterns about launch sites.


Let's first import required Python packages for this lab:

In [4]:
import folium
import pandas as pd

In [6]:
# Import folium MarkerCluster plugin
from folium.plugins import MarkerCluster
# Import folium MousePosition plugin
from folium.plugins import MousePosition
# Import folium DivIcon plugin
from folium.features import DivIcon

If you need to refresh your memory about folium, you may download and refer to this previous folium lab:

In [9]:
URL = 'https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/datasets/spacex_launch_geo.csv'

spacex_df=pd.read_csv(URL)
spacex_df.head(5)

,Flight Number,Date,Time (UTC),Booster Version,Launch Site,Payload,Payload Mass (kg),Orbit,Customer,Landing Outcome,class,Lat,Long
0,1,2010-06-04,18:45:00,F9 v1.0 B0003,CCAFS LC-40,Dragon Spacecraft Qualification Unit,0.0,LEO,SpaceX,Failure (parachute),0,28.562302,-80.577356
1,2,2010-12-08,15:43:00,F9 v1.0 B0004,CCAFS LC-40,"Dragon demo flight C1, two CubeSats, barrel o...",0.0,LEO (ISS),NASA (COTS) NRO,Failure (parachute),0,28.562302,-80.577356
2,3,2012-05-22,7:44:00,F9 v1.0 B0005,CCAFS LC-40,Dragon demo flight C2+,525.0,LEO (ISS),NASA (COTS),No attempt,0,28.562302,-80.577356
3,4,2012-10-08,0:35:00,F9 v1.0 B0006,CCAFS LC-40,SpaceX CRS-1,500.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356
4,5,2013-03-01,15:10:00,F9 v1.0 B0007,CCAFS LC-40,SpaceX CRS-2,677.0,LEO (ISS),NASA (CRS),No attempt,0,28.562302,-80.577356

Now, you can take a look at what are the coordinates for each site.

In [16]:
# Select relevant sub-columns: `Launch Site`, `Lat(Latitude)`, `Long(Longitude)`, `class`
spacex_df = spacex_df[['Launch Site', 'Lat', 'Long', 'class']]
launch_sites_df = spacex_df.groupby(['Launch Site'], as_index=False).first()
launch_sites_df = launch_sites_df[['Launch Site', 'Lat', 'Long']]
launch_sites_df

    Launch Site        Lat        Long
0   CCAFS LC-40  28.562302  -80.577356
1  CCAFS SLC-40  28.563197  -80.576820
2    KSC LC-39A  28.573255  -80.646895
3   VAFB SLC-4E  34.632834 -120.610745

Above coordinates are just plain numbers that can not give you any intuitive insights about where are those launch sites. If you are very good at geography, you can interpret those numbers directly in your mind. If not, that's fine too. Let's visualize those locations by pinning them on a map.

We first need to create a folium Map object, with an initial center location to be NASA Johnson Space Center at Houston, Texas.

In [19]:
# Start location is NASA Johnson Space Center
nasa_coordinate = [29.559684888503615, -95.0830971930759]
site_map = folium.Map(location=nasa_coordinate, zoom_start=10)

In [21]:
site_map

We could use folium.Circle to add a highlighted circle area with a text label on a specific coordinate. For example,

In [27]:
# Create a blue circle at NASA Johnson Space Center's coordinate with a popup label showing its name
circle = folium.Circle(nasa_coordinate, radius=1000, color='#d35400', fill=True).add_child(folium.Popup('NASA Johnson Space Center'))
# Create a blue circle at NASA Johnson Space Center's coordinate with a icon showing its name
marker = folium.map.Marker(
    nasa_coordinate,
    # Create an icon as a text label
    icon=DivIcon(
        icon_size=(20,20),
        icon_anchor=(0,0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'NASA JSC',
        )
    )
site_map.add_child(circle)
site_map.add_child(marker)

and you should find a small yellow circle near the city of Houston and you can zoom-in to see a larger circle.

Now, let's add a circle for each launch site in data frame launch_sites

TODO: Create and add folium.Circle and folium.Marker for each launch site on the site map

An example of folium.Circle:

folium.Circle(coordinate, radius=1000, color='#000000', fill=True).add_child(folium.Popup(...))

An example of folium.Marker:

folium.map.Marker(coordinate, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'label', ))

In [106]:
# Initial the map
site_map = folium.Map(location=nasa_coordinate, zoom_start=5)
# For each launch site, add a Circle object based on its coordinate (Lat, Long) values. In addition, add Launch site name as a popup label
# CCAFS LC-40
coordinate0 = [28.562302, -80.577356]
circle0 = folium.Circle(coordinate0, radius=1000, color='red', fill=True).add_child(folium.Popup('CCAFS LC-40'))
marker0 = folium.map.Marker(coordinate0, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS LC-40', ))

site_map.add_child(circle0)
site_map.add_child(marker0)

# CCAFS SLC-40
coordinate1 = [28.563197, -80.576820]
circle1 = folium.Circle(coordinate1, radius=1100, color='blue', fill=True).add_child(folium.Popup('CCAFS SLC-40'))
marker1 = folium.map.Marker(coordinate1, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'CCAFS SLC-40', ))

site_map.add_child(circle1)
site_map.add_child(marker1)

# KSC LC-39A	28.573255	-80.646895
coordinate2 = [28.573255, -80.646895]
circle2 = folium.Circle(coordinate2, radius=1200, color='purple', fill=True).add_child(folium.Popup('KSC LC-39A'))
marker2 = folium.map.Marker(coordinate2, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'KSC LC-39A', ))

site_map.add_child(circle2)
site_map.add_child(marker2)


# VAFB SLC-4E	34.632834	-120.610745
coordinate3 = [34.632834, -120.610745]
circle3 = folium.Circle(coordinate3, radius=10000, color='green', fill=True).add_child(folium.Popup('VAFB SLC-4E'))
marker3 = folium.map.Marker(coordinate3, icon=DivIcon(icon_size=(20,20),icon_anchor=(0,0), html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' % 'VAFB SLC-4E', ))

site_map.add_child(circle3)
site_map.add_child(marker3)

In [108]:
spacex_df

     Launch Site        Lat        Long  class
0    CCAFS LC-40  28.562302  -80.577356      0
1    CCAFS LC-40  28.562302  -80.577356      0
2    CCAFS LC-40  28.562302  -80.577356      0
3    CCAFS LC-40  28.562302  -80.577356      0
4    CCAFS LC-40  28.562302  -80.577356      0
5    CCAFS LC-40  28.562302  -80.577356      0
6    CCAFS LC-40  28.562302  -80.577356      0
7    CCAFS LC-40  28.562302  -80.577356      0
8    CCAFS LC-40  28.562302  -80.577356      0
9    CCAFS LC-40  28.562302  -80.577356      0
10   CCAFS LC-40  28.562302  -80.577356      0
11   CCAFS LC-40  28.562302  -80.577356      0
12   CCAFS LC-40  28.562302  -80.577356      0
13   CCAFS LC-40  28.562302  -80.577356      0
14   CCAFS LC-40  28.562302  -80.577356      0
15   CCAFS LC-40  28.562302  -80.577356      0
16   CCAFS LC-40  28.562302  -80.577356      0
17   CCAFS LC-40  28.562302  -80.577356      1
18   CCAFS LC-40  28.562302  -80.577356      1
19   CCAFS LC-40  28.562302  -80.577356      0
20   CCAFS LC-40  28.562302  -80.577356      1
21   CCAFS LC-40  28.562302  -80.577356      1
22   CCAFS LC-40  28.562302  -80.577356      1
23   CCAFS LC-40  28.562302  -80.577356      0
24   CCAFS LC-40  28.562302  -80.577356      1
25   CCAFS LC-40  28.562302  -80.577356      1
26   VAFB SLC-4E  34.632834 -120.610745      0
27   VAFB SLC-4E  34.632834 -120.610745      0
28   VAFB SLC-4E  34.632834 -120.610745      1
29   VAFB SLC-4E  34.632834 -120.610745      1
30   VAFB SLC-4E  34.632834 -120.610745      1
31   VAFB SLC-4E  34.632834 -120.610745      1
32   VAFB SLC-4E  34.632834 -120.610745      0
33   VAFB SLC-4E  34.632834 -120.610745      0
34   VAFB SLC-4E  34.632834 -120.610745      0
35   VAFB SLC-4E  34.632834 -120.610745      0
36    KSC LC-39A  28.573255  -80.646895      1
37    KSC LC-39A  28.573255  -80.646895      0
38    KSC LC-39A  28.573255  -80.646895      1
39    KSC LC-39A  28.573255  -80.646895      1
40    KSC LC-39A  28.573255  -80.646895      0
41    KSC LC-39A  28.573255  -80.646895      1
42    KSC LC-39A  28.573255  -80.646895      1
43    KSC LC-39A  28.573255  -80.646895      0
44    KSC LC-39A  28.573255  -80.646895      1
45    KSC LC-39A  28.573255  -80.646895      1
46    KSC LC-39A  28.573255  -80.646895      1
47    KSC LC-39A  28.573255  -80.646895      1
48    KSC LC-39A  28.573255  -80.646895      1
49  CCAFS SLC-40  28.563197  -80.576820      1
50  CCAFS SLC-40  28.563197  -80.576820      1
51  CCAFS SLC-40  28.563197  -80.576820      0
52  CCAFS SLC-40  28.563197  -80.576820      0
53  CCAFS SLC-40  28.563197  -80.576820      0
54  CCAFS SLC-40  28.563197  -80.576820      1
55  CCAFS SLC-40  28.563197  -80.576820      0

In [68]:
for a,b in zip(launch_sites_df.Lat, launch_sites_df.Long):
    print(a,b)

#launch_sites_df[:1]
#launch_sites_df[:1]

28.56230197 -80.57735648
28.56319718 -80.57682003
28.57325457 -80.64689529
34.63283416 -120.6107455

In [76]:
print(launch_sites_df.Lat[0],",", launch_sites_df.Long[0])

28.56230197 , -80.57735648

In [88]:
for i in launch_sites_df.index:
    print(f"{launch_sites_df.Lat[i]},{launch_sites_df.Long[i]}")


#print(f"{launch_sites_df.Lat[0]},{launch_sites_df.Long[0]}")

28.56230197,-80.57735648
28.56319718,-80.57682003
28.57325457,-80.64689529
34.63283416,-120.6107455

In [86]:
cords

'34.63283416,-120.6107455'

In [33]:
site_map

Now, you can explore the map by zoom-in/out the marked areas , and try to answer the following questions:

Are all launch sites in proximity to the Equator line?
Are all launch sites in very close proximity to the coast?
Also please try to explain your findings.

In [110]:
# Task 2: Mark the success/failed launches for each site on the map
marker_cluster = MarkerCluster()
site_map.add_child(marker_cluster)

def assign_marker_color(launch_outcome):
    if launch_outcome == 1:
        return 'green'
    else:
        return 'red'

spacex_df['marker_color'] = spacex_df['class'].apply(assign_marker_color)

#Then add each launch marker:
for index, record in spacex_df.iterrows():
    marker = folium.Marker(
        location=[record['Lat'], record['Long']],
        icon=folium.Icon(color='white', icon_color=record['marker_color'])
    )

    marker_cluster.add_child(marker)

site_map

# TASK 3: Calculate the distances between a launch site to its proximities

Next, we need to explore and analyze the proximities of launch sites.

Let's first add a MousePosition on the map to get coordinate for a mouse over a point on the map. As such, while you are exploring the map, you can easily find the coordinates of any points of interests (such as railway)

In [122]:
# Add Mouse Position to get the coordinate (Lat, Long) for a mouse over on the map
formatter = "function(num) {return L.Util.formatNum(num, 5);};"
mouse_position = MousePosition(
    position='topright',
    separator=' Long: ',
    empty_string='NaN',
    lng_first=False,
    num_digits=20,
    prefix='Lat:',
    lat_formatter=formatter,
    lng_formatter=formatter,
)

site_map.add_child(mouse_position)

site_map

In [124]:

lat1 = 34.63283416
lon1 = -120.6107455
lat2 = 34.63132
lon2 = -120.63141

from math import sin, cos, sqrt, atan2, radians

def calculate_distance(lat1, lon1, lat2, lon2):
    # approximate radius of earth in km
    R = 6373.0

    lat1 = radians(lat1)
    lon1 = radians(lon1)
    lat2 = radians(lat2)
    lon2 = radians(lon2)

    dlon = lon2 - lon1
    dlat = lat2 - lat1

    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))

    distance = R * c
    return distance

In [128]:
launch_site_lat = 34.63283416
launch_site_lon = -120.6107455

coastline_lat = 34.51575
coastline_lon = -120.50577

distance_coastline = calculate_distance(
    launch_site_lat,
    launch_site_lon,
    coastline_lat,
    coastline_lon
)

launch_site_coordinate = [launch_site_lat, launch_site_lon]
coastline_coordinate = [coastline_lat, coastline_lon]

distance_marker = folium.Marker(
    coastline_coordinate,
    icon=DivIcon(
        icon_size=(80, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' 
             % "{:10.2f} KM".format(distance_coastline),
    )
)

lines = folium.PolyLine(
    locations=[launch_site_coordinate, coastline_coordinate],
    weight=2,
    color='blue'
)

site_map.add_child(distance_marker)
site_map.add_child(lines)

site_map

In [138]:
# Create a marker with distance to a closest city, railway, highway, etc.
# Draw a line between the marker to the launch site
launch_site_lat = 34.63283416
launch_site_lon = -120.6107455

city_lat = 34.64768
city_lon = -120.45814

distance_city = calculate_distance(
    launch_site_lat,
    launch_site_lon,
    city_lat,
    city_lon
)

launch_site_coordinate = [launch_site_lat, launch_site_lon]
city_coordinate = [city_lat, city_lon]

distance_marker2 = folium.Marker(
    city_coordinate,
    icon=DivIcon(
        icon_size=(80, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' 
             % "{:10.2f} KM".format(distance_city),
    )
)

lines2 = folium.PolyLine(
    locations=[launch_site_coordinate, city_coordinate],
    weight=2,
    color='blue'
)

site_map.add_child(distance_marker2)
site_map.add_child(lines2)

#highway
highway_lat = 34.70701
highway_lon = -120.48561

distance_highway = calculate_distance(
    launch_site_lat,
    launch_site_lon,
    highway_lat,
    highway_lon
)

launch_site_coordinate = [launch_site_lat, launch_site_lon]
highway_coordinate = [highway_lat, highway_lon]

distance_marker3 = folium.Marker(
    highway_coordinate,
    icon=DivIcon(
        icon_size=(80, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' 
             % "{:10.2f} KM".format(distance_highway),
    )
)

lines3 = folium.PolyLine(
    locations=[launch_site_coordinate, highway_coordinate],
    weight=2,
    color='blue'
)

site_map.add_child(distance_marker3)
site_map.add_child(lines3)

#railway
railway_lat = 34.63385
railway_lon = -120.62467

distance_railway = calculate_distance(
    launch_site_lat,
    launch_site_lon,
    railway_lat,
    railway_lon
)

launch_site_coordinate = [launch_site_lat, launch_site_lon]
railway_coordinate = [railway_lat, railway_lon]

distance_marker4 = folium.Marker(
    railway_coordinate,
    icon=DivIcon(
        icon_size=(80, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' 
             % "{:10.2f} KM".format(distance_railway),
    )
)

lines4 = folium.PolyLine(
    locations=[launch_site_coordinate, railway_coordinate],
    weight=2,
    color='blue'
)

site_map.add_child(distance_marker4)
site_map.add_child(lines4)

#coastline
coastline_lat = 34.63497
coastline_lon = -120.62531

distance_coastline = calculate_distance(
    launch_site_lat,
    launch_site_lon,
    coastline_lat,
    coastline_lon
)

launch_site_coordinate = [launch_site_lat, launch_site_lon]
coastline_coordinate = [coastline_lat, coastline_lon]

distance_marker5 = folium.Marker(
    coastline_coordinate,
    icon=DivIcon(
        icon_size=(80, 20),
        icon_anchor=(0, 0),
        html='<div style="font-size: 12; color:#d35400;"><b>%s</b></div>' 
             % "{:10.2f} KM".format(distance_coastline),
    )
)

lines5 = folium.PolyLine(
    locations=[launch_site_coordinate, coastline_coordinate],
    weight=2,
    color='blue'
)

site_map.add_child(distance_marker5)
site_map.add_child(lines5)

site_map